# Generated by Django 3.2.9 on 2021-11-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_tool', '0010_auto_20211120_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', unique=True, max_length=100),
        ),
        # migrations.AlterUniqueTogether(
        #     name='assignment',
        #     unique_together={('title', 'classroom')},
        # ),
    ]
