# Generated by Django 3.2.9 on 2021-11-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission_tool', '0011_auto_20211120_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_tool.user')),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_profiles')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission_tool.user')),
                ('emp_id', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher_profiles')),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
