# Generated by Django 3.2.9 on 2021-11-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_tool', '0012_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, default='/student_profiles/placeholder.png', null=True, upload_to='student_profiles'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='image',
            field=models.ImageField(blank=True, default='/teacher_profiles/placeholder.png', null=True, upload_to='teacher_profiles'),
        ),
    ]
