# Generated by Django 3.2.9 on 2021-11-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission_tool', '0021_alter_assignment_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('title', 'classroom')},
        ),
    ]
