export const CLASSROOM_LIST_REQUEST = 'CLASSROOM_LIST_REQUEST';
export const CLASSROOM_LIST_SUCCESS = 'CLASSROOM_LIST_SUCCESS';
export const CLASSROOM_LIST_FAIL = 'CLASSROOM_LIST_FAIL';

export const CLASSROOM_DETAILS_REQUEST = 'CLASSROOM_DETAILS_REQUEST';
export const CLASSROOM_DETAILS_SUCCESS = 'CLASSROOM_DETAILS_SUCCESS';
export const CLASSROOM_DETAILS_FAIL = 'CLASSROOM_DETAILS_FAIL';

export const CLASSROOM_CREATE_REQUEST = 'CLASSROOM_CREATE_REQUEST';
export const CLASSROOM_CREATE_SUCCESS = 'CLASSROOM_CREATE_SUCCESS';
export const CLASSROOM_CREATE_FAIL = 'CLASSROOM_CREATE_FAIL';

export const CLASSROOM_JOIN_REQUEST = 'CLASSROOM_JOIN_REQUEST';
export const CLASSROOM_JOIN_SUCCESS = 'CLASSROOM_JOIN_SUCCESS';
export const CLASSROOM_JOIN_FAIL = 'CLASSROOM_JOIN_FAIL';

export const CLASSROOM_DELETE_REQUEST = 'CLASSROOM_DELETE_REQUEST';
export const CLASSROOM_DELETE_SUCCESS = 'CLASSROOM_DELETE_SUCCESS';
export const CLASSROOM_DELETE_FAIL = 'CLASSROOM_DELETE_FAIL';

export const CLASSROOM_LEAVE_REQUEST = 'CLASSROOM_LEAVE_REQUEST';
export const CLASSROOM_LEAVE_SUCCESS = 'CLASSROOM_LEAVE_SUCCESS';
export const CLASSROOM_LEAVE_FAIL = 'CLASSROOM_LEAVE_FAIL';
