export const SUBMISSION_LIST_REQUEST = 'SUBMISSION_LIST_REQUEST';
export const SUBMISSION_LIST_SUCCESS = 'SUBMISSION_LIST_SUCCESS';
export const SUBMISSION_LIST_FAIL = 'SUBMISSION_LIST_FAIL';

export const SUBMISSION_DETAILS_REQUEST = 'SUBMISSION_DETAILS_REQUEST';
export const SUBMISSION_DETAILS_SUCCESS = 'SUBMISSION_DETAILS_SUCCESS';
export const SUBMISSION_DETAILS_FAIL = 'SUBMISSION_DETAILS_FAIL';

export const SUBMISSION_CREATE_REQUEST = 'SUBMISSION_CREATE_REQUEST';
export const SUBMISSION_CREATE_SUCCESS = 'SUBMISSION_CREATE_SUCCESS';
export const SUBMISSION_CREATE_FAIL = 'SUBMISSION_CREATE_FAIL';

export const SUBMISSION_UPDATE_REQUEST = 'SUBMISSION_UPDATE_REQUEST';
export const SUBMISSION_UPDATE_SUCCESS = 'SUBMISSION_UPDATE_SUCCESS';
export const SUBMISSION_UPDATE_FAIL = 'SUBMISSION_UPDATE_FAIL';
